[project]
name = "mlops-du"
version = "0.1.0"
description = "MLOps course assignments monorepo"
readme = "README.md"
requires-python = ">=3.12"

[project.optional-dependencies]
dev = [
    "ruff>=0.12.0",
]

[tool.uv.workspace]
members = ["assignments/*"]
