version: '3'

tasks:
  movie-sentiment:
    desc: Run the movie sentiment analysis model training and streamlit app
    dir: assignments/movie-sentiment
    cmds:
      - uv sync --project assignments/movie-sentiment
      - uv pip install -e .
      - uv run python src/main.py 