version: '3'

tasks:
  # Internal validator for env vars / projects args
  _validate:
    internal: true
    silent: true
    cmds:
      - |
        if [ -z "{{.PROJ}}" ]; then
          echo "❌ Error: PROJ variable is required"
          echo "Usage: task <task-name> PROJ=<project-name>"
          exit 1
        fi
      - |
        # Check if PROJ_DIR is set (from command line or parent task)
        if [ -n "{{.PROJ_DIR}}" ]; then
          # Use the provided PROJ_DIR
          if [ ! -d "{{.PROJ_DIR}}" ]; then
            echo "❌ Error: Directory {{.PROJ_DIR}} does not exist"
            echo "Make sure the project's directory exists or override with PROJ_DIR=<path>"
            exit 1
          fi
        else
          # Use the default value
          if [ ! -d "assignments/{{.PROJ}}" ]; then
            echo "❌ Error: Directory assignments/{{.PROJ}} does not exist"
            echo "Make sure the project's directory exists or override with PROJ_DIR=<path>"
            exit 1
          fi
        fi

  # Assignment 1 - Local Execution (Without Docker)
  execute-proj:
    desc: Run the project locally with uv (`task execute-proj PROJ=<project-name>`)
    deps: [_validate]
    silent: true
    vars:
      PROJ_DIR: 'assignments/{{.PROJ}}'
    dir: '{{.PROJ_DIR}}' 
    cmds:
      - uv sync --package {{.PROJ}}
      - uv pip install -e .
      - |
        if [ "{{.PROJ}}" = "fastapi-movie" ]; then
          uv run uvicorn src.main:app
        else
          uv run python src/main.py
        fi

  # Assignment 2 - Docker Execution
  execute-proj-docker:
    desc: Build and run the project in Docker (`task execute-proj-docker PROJ=<project-name>`)
    deps: [_validate]
    silent: true
    vars:
      PROJ_DIR: 'assignments/{{.PROJ}}'
      IMG: '{{.PROJ}}'
    dir: '{{.PROJ_DIR}}'
    cmds:
      - docker build -t {{.IMG}} .
      - docker run --rm -p 8501:8501 {{.IMG}}

  build:
    desc: Build the Docker container (`task build PROJ=<project-name>`)
    deps: [_validate]
    silent: true
    vars:
      PROJ_DIR: 'assignments/{{.PROJ}}'
      # IMG variable is redundant but it makes it clear that the Docker image name == project name
      IMG: '{{.PROJ}}'
    # Can override PROJ_DIR in CLI 
    # i.e task execute-proj PROJ=<project-name> PROJ_DIR=<project-directory>  
  
    dir: '{{.PROJ_DIR}}'
    cmds:
      - docker build -t {{.IMG}} .

  run:
    desc: Run the Docker container (`task run PROJ=<project-name>`)
    deps: [_validate]
    silent: true
    vars:
      PROJ_DIR: 'assignments/{{.PROJ}}'
      IMG: '{{.PROJ}}'
    dir: '{{.PROJ_DIR}}'
    cmds:
      - docker run --rm -p 8501:8501 {{.IMG}}

  clean:
    desc: Remove Docker image (`task clean PROJ=<project-name>`)
    deps: [_validate]
    silent: true
    vars:
      PROJ_DIR: 'assignments/{{.PROJ}}'
      IMG: '{{.PROJ}}'
    cmds:
      - docker rmi {{.IMG}} || true

  clean-artifacts:
    desc: Delete .log, .pkl, and .csv from /assets (`task clean-artifacts PROJ=<project-name>`)
    deps: [_validate]
    silent: true
    vars:
      PROJ_DIR: 'assignments/{{.PROJ}}'
    cmds:
      - rm -rf {{.PROJ_DIR}}/assets/logs/*.log
      - rm -rf {{.PROJ_DIR}}/assets/models/*.pkl
      - rm -rf {{.PROJ_DIR}}/assets/data/*.csv
      - echo "Artifacts cleaned successfully!"