# Configuration file for movie sentiment analysis project

default:
  main_logging:
    handler: "file"
    path: "assets/logs/app.log"
  kaggle:
    dataset_path: "lakshmi25npathi/imdb-dataset-of-50k-movie-reviews"
    dataset_name: "IMDB Dataset.csv"

development:
  paths: # Local file paths
    data: "assets/data/IMDB Dataset.csv"
    model: "assets/models/sentiment_model.pkl"
  prediction_logging:
    handler: "file"
    path: "assets/logs/prediction_logs.json"    

production:
  paths: # S3 paths
    data: "data/IMDB Dataset.csv"
    model: "models/sentiment_model.pkl"
  prediction_logging:
    handler: "dynamodb"
    table_name: "sentiment_predictions"
